name: Build Api Dev

on:
  push:
    branches: 
      - main
    paths:
      - 'MyFeedback/**'
    
defaults:
  run:
    working-directory: ./MyFeedback

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#     O Projeto ainda não possui testes
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
